In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv')

In [4]:
df

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [5]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [6]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X[:,2] = le.fit_transform(X[:,2])

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],remainder='passthrough')
X = ct.fit_transform(X)

In [9]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size =0.2, random_state= 42)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
ann = tf.keras.models.Sequential()

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #nonbinary softmax
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy') #nonbinary categorical_crossentropy

In [14]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 919us/step - loss: 0.6733 - accuracy: 0.5830
Epoch 2/100
250/250 [==============================] - 0s 905us/step - loss: 0.4830 - accuracy: 0.7943
Epoch 3/100
250/250 [==============================] - 0s 872us/step - loss: 0.4512 - accuracy: 0.7985
Epoch 4/100
250/250 [==============================] - 0s 900us/step - loss: 0.4398 - accuracy: 0.8046
Epoch 5/100
250/250 [==============================] - 0s 844us/step - loss: 0.4319 - accuracy: 0.8100
Epoch 6/100
250/250 [==============================] - 0s 830us/step - loss: 0.4248 - accuracy: 0.8185
Epoch 7/100
250/250 [==============================] - 0s 897us/step - loss: 0.4176 - accuracy: 0.8229
Epoch 8/100
250/250 [==============================] - 0s 900us/step - loss: 0.4085 - accuracy: 0.8257
Epoch 9/100
250/250 [==============================] - 0s 903us/step - loss: 0.3961 - accuracy: 0.8322
Epoch 10/100
250/250 [==============================] - 0s 875us/step - l

In [15]:
ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5

array([[False]])

In [16]:
y_pred = ann.predict(X_test)
y_pred = (y_pred> 0.5)

In [23]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [22]:
accuracy_score(y_test, y_pred)

0.8635

In [25]:
confusion_matrix(y_test, y_pred)

array([[1535,   72],
       [ 201,  192]])